WITH WEEKLY_ORDER_CUSTOMERS AS(
SELECT
Created_at,
Order_amount,
ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY CREATED_AT) AS VISIT_NUMBER
FROM {{ ref('stg_orders') }}
)

SELECT
EXTRACT(YEAR FROM created_at) as order_year,
EXTRACT(WEEK FROM created_at) as order_week
, SUM(CASE WHEN VISIT_NUMBER = 1 THEN ORDER_AMOUNT ELSE 0 END) AS FIRST_VISIT_REVENUE
, SUM(CASE WHEN VISIT_NUMBER > 1 THEN ORDER_AMOUNT ELSE 0 END) AS RETURNING_REVENUE
FROM WEEKLY_ORDER_CUSTOMERS
GROUP BY 1,2
